package com.incoresoft.dilijanCustomization.bootstrap;

import com.incoresoft.dilijanCustomization.config.UnknownListRegistry;
import com.incoresoft.dilijanCustomization.repository.FaceApiRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.ApplicationRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Ensures a face list named 'unknownAutoGenerated' exists at startup.
 * Saves its ID into UnknownListRegistry for global use.
 */
@Configuration
@RequiredArgsConstructor
@Slf4j
public class UnknownListInitializer {

    private final FaceApiRepository faceApiRepository;
    private final UnknownListRegistry unknownListRegistry;

    private static final String UNKNOWN_LIST_NAME = "unknownAutoGenerated";
    private static final String UNKNOWN_LIST_COMMENT = "Autocreated at app startup for unknown persons";

    @Bean
    public ApplicationRunner ensureUnknownList() {
        return args -> {
            var existing = faceApiRepository.findListByName(UNKNOWN_LIST_NAME);
            long id;
            if (existing.isPresent()) {
                id = existing.get().getId();
                log.info("Unknown list '{}' found with id={}", UNKNOWN_LIST_NAME, id);
            } else {
                id = faceApiRepository.createFaceList(UNKNOWN_LIST_NAME, UNKNOWN_LIST_COMMENT);
                log.info("Unknown list '{}' created with id={}", UNKNOWN_LIST_NAME, id);
            }
            unknownListRegistry.set(id);
        };
    }
}
