package com.incoresoft.dilijanCustomization.domain.unknown.service;

import com.incoresoft.dilijanCustomization.config.UnknownListRegistry;
import com.incoresoft.dilijanCustomization.config.UnknownProps;
import com.incoresoft.dilijanCustomization.domain.shared.dto.DetectionDto;
import com.incoresoft.dilijanCustomization.domain.shared.dto.ListItemDto;
import com.incoresoft.dilijanCustomization.domain.shared.dto.ListItemsResponse;
import com.incoresoft.dilijanCustomization.domain.unknown.dto.FaceEventDto;
import com.incoresoft.dilijanCustomization.domain.unknown.dto.FromDetectionRequest;
import com.incoresoft.dilijanCustomization.repository.FaceApiRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

import java.time.Duration;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.function.Supplier;

@Slf4j
@Service
@RequiredArgsConstructor
public class UnknownPersonService {

    private static final int RECENT_DETECTION_LIMIT = 100;
    private static final int DETECTION_WINDOW_MILLIS = 2000;
    private static final int CLEAN_PAGE_LIMIT = 500;
    private static final Duration UNKNOWN_RETENTION = Duration.ofHours(24);
    private static final String UNKNOWN_PREFIX = "unknown";
    private static final String UNKNOWN_COMMENT = "auto-unknown";

    private final FaceApiRepository repo;
    private final UnknownListRegistry unknownListRegistry;
    private final UnknownProps unknownProps;

    // ADD flow
    public Optional<ListItemDto> handleEventAddIfUnknown(FaceEventDto event) {
        if (event.isInList()) {
            log.info("[ADD] Skip: already in a list (list_id={})", resolveListId(event));
            return Optional.empty();
        }

        List<DetectionDto> candidates = fetchCandidateDetections(event);
        DetectionDto matchingDetection = findMatchingDetection(event, candidates);

        if (!isDetectionSizeEligible(matchingDetection)) {
            return Optional.empty();
        }

        if (!isUniqueDetection(matchingDetection)) {
            log.info("[ADD] Skip: similar face exists in other lists (face_image={})", matchingDetection.getFaceImage());
            return Optional.empty();
        }

        String name = nextUnknownName();
        log.info("[ADD] unique name={}", name);

        ListItemDto item = repo.createListItemFromDetection(
                new FromDetectionRequest(unknownListRegistry.get(), matchingDetection.getId(), name, UNKNOWN_COMMENT));
        log.info("[ADD] created list_item id={}", item.getId());

        return Optional.ofNullable(item);
    }

    // REMOVE flow
    public boolean handleEventRemoveIfUnknown(FaceEventDto event) {
        if (!isUnknownListEvent(event)) {
            log.info("[REMOVE] Skip: not in unknown list or list_item_id missing");
            return false;
        }
        Long listItemId = event.getFace().getListItem().getId();
        repo.deleteListItem(listItemId);
        log.info("[REMOVE] deleted list_item id={}", listItemId);
        return true;
    }

    // nightly clean
    @Scheduled(cron = "0 0 * * * *")
    public void cleanUnknownList() {
        long cutoffMillis = System.currentTimeMillis() - UNKNOWN_RETENTION.toMillis();
        int deleted = 0;
        int kept = 0;

        for (ListItemDto listItem : fetchListItems(CLEAN_PAGE_LIMIT)) {
            if (!isAutogenerated(listItem)) {
                kept++;
                continue;
            }

            Long createdAtMillis = listItem.resolveCreatedAtMillis();
            if (createdAtMillis == null || createdAtMillis > cutoffMillis) {
                kept++;
                continue;
            }

            if (attemptDelete(listItem)) {
                deleted++;
            }
        }

        log.info("[CLEAN] Unknown list retention applied (deleted={}, kept={})", deleted, kept);
    }

    private String nextUnknownName() {
        ListItemsResponse resp = repo.getListItems(unknownListRegistry.get(), UNKNOWN_PREFIX, "", 0, 1, "asc", "name");
        int total = resp.getTotal() == null ? 0 : resp.getTotal();
        return UNKNOWN_PREFIX + (total + 1);
    }

    private List<DetectionDto> fetchCandidateDetections(FaceEventDto event) {
        if (event.getTimestamp() == null) {
            throw new IllegalStateException("Face event timestamp is required");
        }
        long windowStart = event.getTimestamp() - DETECTION_WINDOW_MILLIS;
        long windowEnd = event.getTimestamp() + DETECTION_WINDOW_MILLIS;
        List<DetectionDto> detections = Optional.ofNullable(
                        repo.getRecentDetections(RECENT_DETECTION_LIMIT, "asc", windowStart, windowEnd).getData())
                .orElse(List.of());
        detections.forEach(d -> log.info("[ADD] candidate id={} face_image={}", d.getId(), d.getFaceImage()));
        return detections;
    }

    private DetectionDto findMatchingDetection(FaceEventDto event, List<DetectionDto> detections) {
        return detections.stream()
                .filter(d -> Objects.equals(d.getFaceImage(), event.getFaceImage()))
                .peek(d -> log.info("[ADD] MATCH id={}", d.getId()))
                .findFirst()
                .orElseThrow(() -> new IllegalStateException(
                        "No detection with matching face_image: " + event.getFaceImage()));
    }


    private boolean isDetectionSizeEligible(DetectionDto detection) {
        int cameraResolutionHeight = unknownProps.getCameraResolutionHeight();
        int desiredImageHeight = unknownProps.getDesiredImageHeight();

        if (desiredImageHeight <= 0) {
            return true;
        }

        if (cameraResolutionHeight <= 0) {
            log.warn("[ADD] Skip size filter: invalid cameraResolutionHeight={}", cameraResolutionHeight);
            return true;
        }

        List<Double> box = Optional.ofNullable(detection).map(DetectionDto::getBox).orElse(List.of());
        if (box.size() < 4 || box.get(1) == null || box.get(3) == null) {
            log.info("[ADD] Skip: detection box is missing/invalid (detection_id={}, box={})",
                    detection == null ? null : detection.getId(), box);
            return false;
        }

        double boxHeightRatio = box.get(3) - box.get(1);
        int faceHeightPixels = (int) Math.round(boxHeightRatio * cameraResolutionHeight);
        if (faceHeightPixels < desiredImageHeight) {
            log.info("[ADD] Skip: detection box too small (detection_id={}, face_height_px={}, min_px={})",
                    detection.getId(), faceHeightPixels, desiredImageHeight);
            return false;
        }

        return true;
    }

    private boolean isUniqueDetection(DetectionDto detection) {
        return downloadBytes(detection)
                .map(bytes -> repo.isFaceUniqueInLists(bytes, null))
                .orElse(false);
    }

    private Optional<byte[]> downloadBytes(DetectionDto detection) {
        return Optional.ofNullable(detection)
                .map(DetectionDto::getFaceImage)
                .filter(img -> !img.isBlank())
                .map(this::downloadImageSafely);
    }

    private byte[] downloadImageSafely(String imagePath) {
        return executeSafe(() -> repo.downloadStorageObject(imagePath), new byte[0]);
    }

    private <T> T executeSafe(Supplier<T> supplier, T fallback) {
        try {
            return supplier.get();
        } catch (Exception e) {
            log.warn("[ADD] Failed to download face image: {}", e.getMessage());
            return fallback;
        }
    }

    private boolean isUnknownListEvent(FaceEventDto event) {
        return event.isInList()
                && event.getFace() != null
                && event.getFace().getListItem() != null
                && event.getFace().getListItem().getList() != null
                && Objects.equals(event.getFace().getListItem().getList().getId(), unknownListRegistry.get())
                && event.getFace().getListItem().getId() != null;
    }

    private Long resolveListId(FaceEventDto event) {
        return Optional.ofNullable(event)
                .map(FaceEventDto::getFace)
                .map(FaceEventDto.FacePayload::getListItem)
                .map(FaceEventDto.ListItemRef::getList)
                .map(FaceEventDto.PersonListRef::getId)
                .orElse(null);
    }

    private List<ListItemDto> fetchListItems(int limit) {
        List<ListItemDto> allItems = new java.util.ArrayList<>();
        int offset = 0;

        while (true) {
            ListItemsResponse response = repo.getListItems(unknownListRegistry.get(), "", "", offset, limit, "asc", "name");
            List<ListItemDto> pageItems = Optional.ofNullable(response)
                    .map(ListItemsResponse::getData)
                    .orElse(List.of());
            if (pageItems.isEmpty()) {
                break;
            }

            allItems.addAll(pageItems);
            if (pageItems.size() < limit) {
                break;
            }
            offset += limit;
        }
        return allItems;
    }

    private boolean isAutogenerated(ListItemDto listItemDto) {
        return listItemDto != null && UNKNOWN_COMMENT.equalsIgnoreCase(listItemDto.getComment());
    }

    private boolean attemptDelete(ListItemDto listItemDto) {
        if (listItemDto == null || listItemDto.getId() == null) {
            return false;
        }
        try {
            repo.deleteListItem(listItemDto.getId());
            return true;
        } catch (Exception ex) {
            log.warn("Delete failed id={}: {}", listItemDto.getId(), ex.getMessage());
            return false;
        }
    }
}
