package com.incoresoft.dilijanCustomization.bootstrap;

import com.incoresoft.dilijanCustomization.config.UnknownListRegistry;
import com.incoresoft.dilijanCustomization.domain.shared.dto.FaceListDto;
import com.incoresoft.dilijanCustomization.repository.FaceApiRepository;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

class UnknownListInitializerTest {

    @Test
    void usesExistingListWhenFound() throws Exception {
        FaceApiRepository repo = mock(FaceApiRepository.class);
        UnknownListRegistry registry = new UnknownListRegistry();
        FaceListDto dto = new FaceListDto();
        dto.setId(5L);
        when(repo.findListByName("unknownAutoGenerated")).thenReturn(Optional.of(dto));

        UnknownListInitializer initializer = new UnknownListInitializer(repo, registry);
        initializer.ensureUnknownList().run(null);

        verify(repo, never()).createFaceList(anyString(), anyString());
        assertEquals(5L, registry.get());
    }

    @Test
    void createsListWhenMissing() throws Exception {
        FaceApiRepository repo = mock(FaceApiRepository.class);
        UnknownListRegistry registry = new UnknownListRegistry();
        when(repo.findListByName("unknownAutoGenerated")).thenReturn(Optional.empty());
        when(repo.createFaceList(anyString(), anyString())).thenReturn(42L);

        UnknownListInitializer initializer = new UnknownListInitializer(repo, registry);
        initializer.ensureUnknownList().run(null);

        verify(repo).createFaceList("unknownAutoGenerated", "Autocreated at app startup for unknown persons");
        assertEquals(42L, registry.get());
    }
}
